### PR TITLE
travis: add 1.x to go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by dlorenc** [comment]
Would you mind explaining what this is for?

**Comment by dvrkps** [comment]
@dlorenc Sure, 1.x means latest stable go version. 

https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use

**Comment by dvrkps** [comment]
@nkubala ping :)

**Comment by dvrkps** [comment]
@nkubala can you rebase ? i delete my branch already.

**Comment by nkubala** [comment]
Can't rebase since the branch has already been deleted. Closing in favor of https://github.com/GoogleCloudPlatform/container-diff/pull/158

**Pull request closed without merging**
