### PR TITLE
added boilerplate to all files and a check in the test .sh file

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
fixes #43

**Comment by aaron-prindle** [comment]
I changed the license to use `Google, Inc`.  boilerplate.py and all the associated files are used to run a test in test.sh that makes sure that any files that are added to the repo have the the boilerplate.

**Comment by nkubala** [comment]
looks fine, but can you check out the travis failure?

**Comment by aaron-prindle** [comment]
PTAL

**Pull request merged**
