### PR TITLE
getPrepperForImage: strip prefixes prior to reference validation

### PR DESCRIPTION
**Pull request by vrothberg**
Strip the `daemon://` and `remote://` prefix prior to validating the
reference.  Otherwise, the validation will fail unconditionally.

Fixes: #183
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
The Travis failure is curious as the `apt_sorted_differ` (and other failing tests) seem to use the json files for the node test.

```
    --- FAIL: TestDiffAndAnalysis/apt_sorted_differ (23.84s)
    	integration_test.go:218: Error actual output does not match expected.  
    		
    		Expected: [
    		  {
    		    "Image": "gcr.io/gcp-runtimes/node-modified",
```

**Comment by vrothberg** [comment]
I can't reproduce the Travis failure on my machine:
```
    --- FAIL: TestDiffAndAnalysis/apt_sorted_differ (18.24s)
    	integration_test.go:209: Error running command: Error running command [analyze gcr.io/gcp-runtimes/node-modified --type=node -j]: exit status 1 Stderr: Retrieving image gcr.io/gcp-runtimes/node-modified from source Cloud Registry
    		time="2018-01-31T14:36:36Z" level=error msg="Error processing image: unexpected EOF"
```

**Comment by dlorenc** [comment]
I think there were a few issues that are all fixed here: #187

**Comment by vrothberg** [comment]
@dlorenc Awesome, I'm closing this one then.

**Pull request closed without merging**
