### PR TITLE
Adding known issue of etc/docker/certs documentation.

### PR DESCRIPTION
**Pull request by abbytiz**
@cftorres @aaron-prindle @nkubala

### CODE REVIEW

**Comment by abbytiz** [comment]
fixes #21

**Comment by aaron-prindle** [comment]
LGTM

**Comment by duggelz** [comment]
`rm -rf /etc/docker`? This sounds like something important? What exactly am I wiping out?

```
$ sudo ls -al /etc/docker
total 24
drwx------   2 root root  4096 Sep  8  2015 .
drwxr-xr-x 186 root root 16384 Aug 18 16:10 ..
-rw-------   1 root root   281 Sep  8  2015 key.json

$ sudo cat /etc/docker/key.json
{
    "crv": "P-256",
    "d": "long string off stuff",
    "kid": "long string of stuff",
    "kty": "EC",
    "x": "long string of stuff",
    "y": "long string of stuff"
}
```

**Comment by nkubala** [comment]
Hmm, I wonder if we could get away with doing something like `sudo chmod -R 755 /etc/docker`? @aaron-prindle @dlorenc @duggelz WDYT

**Pull request merged**
